# -*- coding: utf-8 -*-
"""AI DUNGEON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PqE9FnUaOeOM5ZKwItSOOzzfjbT1zU-d
"""

import random

# Game state
current_room = None
game_over = False

# Define the game rooms
rooms = {
    'start': {
        'description': 'You are in a dark room. There is a door in front of you.',
        'actions': {
            'open door': 'You open the door and enter a long corridor.',
            'look around': 'You see a dimly lit room with a table and chairs.',
            'quit': 'You decide to quit the game. Goodbye!'
        },
        'next_rooms': ['corridor', 'room']
    },
    'corridor': {
        'description': 'You are in a long corridor.',
        'actions': {
            'go left': 'You turn left and find a locked door.',
            'go right': 'You turn right and see a staircase.',
            'go back': 'You go back to the previous room.'
        },
        'next_rooms': ['locked_door', 'staircase', 'start']
    },
    'room': {
        'description': 'You are in a dimly lit room.',
        'actions': {
            'sit on chair': 'You sit on a chair and relax.',
            'search table': 'You find a key on the table.',
            'go back': 'You go back to the previous room.'
        },
        'next_rooms': ['start']
    },
    'locked_door': {
        'description': 'You see a locked door.',
        'actions': {
            'use key': 'You unlock the door and enter a treasure room.',
            'go back': 'You go back to the previous room.'
        },
        'next_rooms': ['treasure_room', 'corridor']
    },
    'staircase': {
        'description': 'You see a staircase leading to another floor.',
        'actions': {
            'climb stairs': 'You climb the stairs and reach the next floor.',
            'go back': 'You go back to the previous room.'
        },
        'next_rooms': ['next_floor', 'corridor']
    },
    'treasure_room': {
        'description': 'Congratulations! You found the treasure room.',
        'actions': {},
        'next_rooms': []
    },
    'next_floor': {
        'description': 'You reached the next floor.',
        'actions': {},
        'next_rooms': []
    }
}

def start_game():
    global current_room, game_over
    current_room = 'start'
    game_over = False
    print('Welcome to the AI Dungeon prototype!')
    print(rooms[current_room]['description'])

def process_input(input_text):
    global current_room, game_over
    actions = rooms[current_room]['actions']
    if input_text in actions:
        print(actions[input_text])
        if input_text == 'quit':
            game_over = True
        else:
            next_room = random.choice(rooms[current_room]['next_rooms'])
            current_room = next_room
            print(rooms[current_room]['description'])
    else:
        print('Invalid action! Try again.')

def game_loop():
    while not game_over:
        user_input = input('Enter your action: ')
        process_input(user_input)

start_game()
game_loop()